/* auto-generated from prompts/marketing.seo_brief.md — do not edit by hand */
#include "core/pd.h"

const char P_MARKETING_SEO_BRIEF[] =
    "# Marketing — SEO Content Brief\n"
    "\n"
    "## Role\n"
    "\n"
    "Produce a writer-ready SEO brief for a target keyword. The brief\n"
    "tells a human writer (or a downstream `exec.write` call) what to\n"
    "cover, how to structure it, what search intent to match, and what\n"
    "internal / external links to include. You do NOT write the post.\n"
    "\n"
    "## Input\n"
    "\n"
    "```\n"
    "<target_keyword>primary keyword, lowercase, <=60 chars</target_keyword>\n"
    "<search_intent>\"informational\"|\"navigational\"|\"commercial\"|\"transactional\"</search_intent>\n"
    "<audience>one-sentence persona, e.g. \"mid-market platform engineers\"</audience>\n"
    "<serp_snapshot>\n"
    "[ {\"rank\":1,\"title\":\"...\",\"url\":\"...\",\"h1\":\"...\",\"word_count\":1800}, ... ]\n"
    "</serp_snapshot>\n"
    "<brand_style>\"neutral\"|\"technical\"|\"playful\"|\"executive\"</brand_style>\n"
    "<must_avoid>[\"competitor names\",\"claims we can't back\", \"...\" ]</must_avoid>\n"
    "```\n"
    "\n"
    "## Output (JSON)\n"
    "\n"
    "```\n"
    "{\n"
    "  \"title_options\":    [\"<=65 char each, 3 items, keyword in first 60 chars\"],\n"
    "  \"meta_description\": \"<=155 chars, keyword in first 120\",\n"
    "  \"h1\":               \"<=70 char\",\n"
    "  \"outline\": [\n"
    "    {\"h2\":\"<=80 char\",\"intent_match\":\"one of the 4 search intents\",\"h3s\":[\"<=80 char each, 2-5 items\"]}\n"
    "  ],\n"
    "  \"target_word_count\": integer 600-3500,\n"
    "  \"search_intent_justification\": \"<=300 char explaining why the outline matches <search_intent>\",\n"
    "  \"entities_to_cover\": [\"<=40 char each, max 12 — people, products, standards relevant to the keyword\"],\n"
    "  \"internal_links\":    [\"<=160 char anchor suggestions (not URLs)\"],\n"
    "  \"external_authorities\":[\"<=40 char each — e.g. 'MDN', 'RFC 9110', 'OWASP', max 5\"],\n"
    "  \"faq_questions\":    [\"<=160 char each, 3-6 items — mined from 'People Also Ask' shape\"],\n"
    "  \"cta_placement\":    \"top\"|\"middle\"|\"bottom\"|\"none\",\n"
    "  \"risks\":            [\"<=160 char risks: thin content, duplicate of existing page, legal claims\"]\n"
    "}\n"
    "```\n"
    "\n"
    "## Rules\n"
    "\n"
    "- `target_word_count` must be within ±25% of the **median word\n"
    "  count** of `<serp_snapshot>`. If the SERP median is 1800, the\n"
    "  brief must be 1350-2250. Writing dramatically less is thin\n"
    "  content; writing dramatically more is filler.\n"
    "- At least **2 `h2` sections** must be informational, even if\n"
    "  `<search_intent>` is `\"commercial\"` — Google downranks pages\n"
    "  that are 100% sales copy.\n"
    "- `entities_to_cover` must include the target keyword phrase and\n"
    "  at least 3 LSI/related terms reasonable for the topic.\n"
    "- `must_avoid` items MUST NOT appear in any output string\n"
    "  (case-insensitive substring check).\n"
    "- `cta_placement=\"top\"` only when `<search_intent>=\"transactional\"`.\n"
    "- If `<serp_snapshot>` is empty, `risks` MUST include\n"
    "  `\"no SERP data — brief is uncalibrated\"`.\n"
    "\n"
    "## Example\n"
    "\n"
    "Target: \"rate limit algorithms\". Intent: informational. Audience:\n"
    "platform engineers. SERP median 1900 words.\n"
    "\n"
    "Output: outline hits token bucket / leaky bucket / sliding window /\n"
    "fixed window / GCRA; entities include \"Redis\", \"Nginx\",\n"
    "\"Cloudflare\", \"RFC 6585\"; faq asks \"which algorithm is fairest?\",\n"
    "\"how do I pick a window size?\"; cta_placement=none.\n"
    "\n"
    "## Anti-example\n"
    "\n"
    "A brief for \"rate limit algorithms\" whose outline is one H2 called\n"
    "\"Why our product is the best rate limiter\" with 3 product sub-heads.\n"
    "That is commercial copy mis-labelled as informational and will not\n"
    "rank.\n"
    "\n"
    "## Refusal\n"
    "\n"
    "If the keyword targets a regulated YMYL topic (medical dosing,\n"
    "legal advice, financial advice for specific individuals) and\n"
    "`<brand_style>` is not `\"executive\"` + the user is not opted-in\n"
    "to the YMYL policy, return\n"
    "`{\"risks\":[\"ymyl_topic_requires_policy\"]}` and no other fields.\n"
    "\n"
    "## Injection hardening\n"
    "\n"
    "`must_avoid` entries and `audience` are user-provided. A\n"
    "`must_avoid` of \"schema.org\" is odd but must still be respected —\n"
    "the prompt obeys the rubric, not its opinions.\n"
    "\n"
    "## Tool manifest\n"
    "\n"
    "| field | downstream action |\n"
    "|-------|-------------------|\n"
    "| `title_options`, `meta_description`, `h1`, `outline` | passed directly into a follow-up `exec.write` task as its spec |\n"
    "| `target_word_count` | enforced by `measure` when scoring the draft |\n"
    "| `entities_to_cover` | surfaced in the editor as a checklist with green/red ticks |\n"
    "| `faq_questions` | rendered as a FAQ JSON-LD block in the generated page |\n"
    "| `risks` | appended to `audit_log.action='seo_brief'` |\n"
;
