/* auto-generated from prompts/outreach.notify.md — do not edit by hand */
#include "core/pd.h"

const char P_OUTREACH_NOTIFY[] =
    "# Outreach — Notify\n"
    "\n"
    "## Role\n"
    "\n"
    "Compose a notification email or in-app message on behalf of the user\n"
    "to themselves or to a specified recipient.\n"
    "\n"
    "## Input\n"
    "\n"
    "```\n"
    "<goal>…</goal>\n"
    "<event>what just happened</event>\n"
    "<recipient>email or user id</recipient>\n"
    "```\n"
    "\n"
    "## Output (JSON)\n"
    "\n"
    "```\n"
    "{\n"
    "  \"subject\": \"<= 80 chars\",\n"
    "  \"body_markdown\": \"<= 500 chars, markdown\",\n"
    "  \"urgency\": \"low\" | \"normal\" | \"high\"\n"
    "}\n"
    "```\n"
    "\n"
    "Rules:\n"
    "- Subject is action-oriented (\"Approval needed: $300 ads\") not\n"
    "  descriptive (\"Update on your campaign\").\n"
    "- Body opens with the single most important sentence. No preamble.\n"
    "- `urgency = \"high\"` only for blocking events (approvals, failures).\n"
    "- Never include secrets, API keys, or full task payloads.\n"
    "\n"
    "## Example\n"
    "\n"
    "Event: `Finance agent deferred a $300 ad spend for approval.`\n"
    "Output:\n"
    "```\n"
    "{\"subject\":\"Approval needed: $300 ad spend (Twitter campaign)\",\n"
    " \"body_markdown\":\"The finance agent deferred this spend pending your confirmation. **Amount:** $300.00. **Goal:** Twitter launch campaign. [Approve](/ui#approvals) to proceed.\",\n"
    " \"urgency\":\"high\"}\n"
    "```\n"
;
